env:
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble
    - GIT_EMAIL: dead-hosts@funilrys.com
    - GIT_NAME: Travis CI
    - secure: JbrXs11XMYzlmv3qPEtu+we4OtSN5AYkdk0yNrcLsPhKTbTXI+dFwjZpw6Sz1UYyqjpPMDpXBDxTqRQa4Dp1bu5LpUeBWcd/yZq/wIJYJy4oTpfiMLuSwNozyobBJH55EdFNXTi8i4B8suEk7S4dQwCahBZt/nAujx8XPhBbZfD8HzJCyPuUs7YSkzu1v6YG/lJE9K1T9KRYEtzm8QFiHh3uHzrew7QRzwnSLQ05BMCdwON+X5XVp+SlUM96fgIgJC7b6dvJqqY7PQvwsyxi6zNyiPIyB3VetiXyUw3JIolBZtQoZfOu0m3IwOEmRFlFnovCmjPJTCtDyysJNpqu3TNPK+/6IhfL9V2hxld4q4d0vSiB5ZY492wkO1KqgXzU17K7bEjPjJ1MZoFtrrZZdXpOJTWjBmPLdBsmpTEAlvXnp3dUxJjgW46hgqImf+dnekh2ECa5Uof2xbAcLrVfvAb/6/eOnQjK+hoMPkNiApS1qk25sZE4FLtzrt9bWz8ua2nqPc339uPylBQr/7x6tuSI/lWZkCvOEzAuHnJOX2TElVWJZvPs0yThm5hXJnFiG/UCjmz3rI87x35VWPtGqoP0Djc6pwqvmJkWhrVuomPWgOkogS3KdSjxsOFFFFjuM3WhqT2U8N2rM+Ejco9rXIZB2Kn0td0vpMImNYpM6uI=
install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${HOME}/miniconda.sh
  - bash ${HOME}/miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda env create -q -f ${TRAVIS_BUILD_DIR}/.environment.yaml
  - source activate iana
  - python --version --version
  - pip --version
  - conda --version

dist: bionic
os: linux
language: generic
script:
  - ./update.py

notifications:
  on_success: change
  on_failure: always
